###
POST {{content_host}}/content/course/list
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "1",
  "publishStatus": "203001"
}

###查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

###
GET {{gateway_host}}/content/course-category/tree-nodes

###新建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "测试",
  "grade": "204001",
  "description": "测试课程创建"
}

###根据id查询课程信息
GET {{content_host}}/content/course/40

###修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 40,
  "name": "SpringBoot核心",
  "users": "Spring Boot初学者",
  "tags": "Spring项目的快速构建",
  "mt": "1-3",
  "st": "1-3-2",
  "grade": "200003",
  "teachmode": "201001",
  "description": "课程系统性地深度探讨 Spring Boot 核心特性，引导小伙伴对 Java 规范的重视，启发对技术原理性的思考，掌握排查问题的技能，以及学习阅读源码的方法和技巧，全面提升研发能力，进军架构师队伍。",
  "pic": "https://cdn.educba.com/academy/wp-content/uploads/2018/08/Spring-BOOT-Interview-questions.jpg",
  "charge": "201001",
  "price": 0.01
}

### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/74/tree-nodes

### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "yhc新章名称 [点击修改]"
}

### 新增课程计划--节
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 290,
  "grade" : 2,
  "pname" : "yhc新小节名称 [点击修改]"
}

### 删除课程计划
DELETE {{content_host}}/content/teachplan/292

### 移动课程计划
POST {{content_host}}/content/teachplan/movedown/259

### 查询课程下所有教师
GET {{content_host}}/content/courseTeacher/list/80

###新增课程下的老师
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": 80,
  "teacherName": "王老",
  "position": "教师职位",
  "introduction": "教师简介"
}
###修改课程下的老师
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 22,
  "courseId": 80,
  "teacherName": "yhc",
  "position": "教师职位",
  "introduction": "教师简介",
  "photograph": null
}
###删除教师
DELETE {{content_host}}/content/courseTeacher/course/80/24

###删除课程
DELETE {{content_host}}/content/course/40





