###
POST {{content_host}}/content/course/list
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "1",
  "publishStatus": "203001"
}

###查询课程分类
GET {{content_host}}/content/course-category/tree-nodes