### 上传图片文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="测试上传文件.png"
Content-Type: application/octet-stream

< C:\Users\86157\Pictures\Screenshots\测试上传文件.png

###上传文件检查
