
#微服务配置
spring:
  application:
    name: system-api
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        # 扩展配置（原 extension-configs）
      - optional:nacos:system-service-${spring.profiles.active}.yaml?group=LearningPlatform&refresh=true
        # 共享配置（原 shared-configs）
      - optional:nacos:swagger-${spring.profiles.active}.yaml?group=LearningPlatform-common&refresh=true
      - optional:nacos:logging-${spring.profiles.active}.yaml?group=LearningPlatform-common&refresh=true
  cloud:
    nacos:
      server-addr: 192.168.130.128:8848
      discovery:
        namespace: dev
        group: LearningPlatform
      config:
        namespace: dev
        group: LearningPlatform
        file-extension: yaml
        refresh-enabled: true







